name: KARaltars
version: '${project.version}'
main: remainworlds.com.karaltars.KARaltars
api-version: 1.19
authors: [ 7Neriys ]
description: create own altars
commands:
  altarreload:
    description: Reload config
    usage: /altarreload
    aliases: [alreload]
  createaltar:
    usage: /createaltar <altarname> <count of blocks>
  addaltarblock:
    usage: /addaltarblock <altarname>
  deletealtar:
    usage: /deletealtar <altarname>